# Generated by Django 4.2.3 on 2023-08-07 01:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategoryProvided',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_price', models.FloatField()),
                ('service_category_id', models.UUIDField()),
                ('laundry_outlet_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField(default=None, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('total_quota', models.IntegerField(default=10)),
                ('amount_of_active_orders', models.IntegerField(default=0)),
                ('amount_of_reviewed_orders', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('outlet_rating', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PredeterminedServiceCategory',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
    ]
