# Generated by Django 4.2.3 on 2023-08-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_laundryoutlet_latitude_laundryoutlet_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryoutlet',
            name='amount_of_received_orders',
            field=models.IntegerField(default=0),
        ),
    ]
