# Generated by Django 4.2.3 on 2023-08-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_laundryoutlet_amount_of_received_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryoutlet',
            old_name='amount_of_received_orders',
            new_name='amount_of_reviewed_orders',
        ),
        migrations.AlterField(
            model_name='laundryoutlet',
            name='outlet_rating',
            field=models.FloatField(default=0),
        ),
    ]
